// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAksLOpUO4-fuMLrSAyshdUwTSmonwI928',
    appId: '1:717617460136:web:77572561e44f640879239d',
    messagingSenderId: '717617460136',
    projectId: 'projectbfa-efbf5',
    authDomain: 'projectbfa-efbf5.firebaseapp.com',
    storageBucket: 'projectbfa-efbf5.appspot.com',
    measurementId: 'G-0W9F19PXQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXaPwPG4kGa0GJI_p2q83AOqFkk7DC3U8',
    appId: '1:717617460136:android:3451501829805f9779239d',
    messagingSenderId: '717617460136',
    projectId: 'projectbfa-efbf5',
    storageBucket: 'projectbfa-efbf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFweDLilxmC7Si2vkK7evtIfdDa-cd7do',
    appId: '1:717617460136:ios:2f65e9e9e9d7ca6c79239d',
    messagingSenderId: '717617460136',
    projectId: 'projectbfa-efbf5',
    storageBucket: 'projectbfa-efbf5.appspot.com',
    iosClientId: '717617460136-v4v5qpfkfvocd9gmnsqk0cpd805rfpbt.apps.googleusercontent.com',
    iosBundleId: 'none',
  );
}
